<?php
/**
 *@var Rafi\Reea\Block\CustomBlock $block
 **/
?>
<?php $order = $block->getOrder(); ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('My Order Comment')) ?></strong>
    </div>
    <div class="block-content">

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php echo $order->getOrderComment(); ?></span>
            </strong>
        </div>

    </div>
</div>
